### PR TITLE
Fix folder/file permissions

### LINKED ISSUE #8: Something went wrong:  open /home/user/.gotify/cli.json: permission denied
gotify creates /home/user/.gotify/ without execute permission and so fails to write the file there.

### PR DESCRIPTION
**Pull request by jmattheis**
Fixes #8

### CODE REVIEW

File: config/readwrite.go [hunk 1]
```diff
@@ -58,6 +58,6 @@ func WriteConfig(location string, conf *Config) error {
 	if err != nil {
 		return err
 	}
-	os.MkdirAll(filepath.Dir(location), 0644)
-	return ioutil.WriteFile(location, bytes, 0644)
+	os.MkdirAll(filepath.Dir(location), 0755)
+	return ioutil.WriteFile(location, bytes, 0755)
```
Comment (eternal-flame-AD) [inline config/readwrite.go]: We do need `x` permission on the directory so the cli can locate it, but I don't think we need `x` for the configuration file itself.
```suggestion
	return ioutil.WriteFile(location, bytes, 0644)
```

Comment (jmattheis) [reply config/readwrite.go]: :+1:
