### PR TITLE
don't exit when current user is unknown

### LINKED ISSUE #13: Cli not useable with cronjob when $USER is missing
The CLI for Linux (amd64 and 386) make an error when running **within a cronjob**. Running from shell does not make any errors. From my point it is the missing environment problem?

This is not working:
```
#!/bin/bash
/opt/gotify-cli-linux-amd64 p -p 1 --url "http://localhost:8080" --token "Axxxxxxxxxxxxxx" -t "Cron Demo" "via Cronjob"
```
This error is occur:
```
user: Current not implemented on linux/amd64
or
user: Current not implemented on linux/386
```
You can solve the problem with an USER  line:
```
#!/bin/bash

export USER=dummy

/opt/gotify-cli-linux-amd64 p -p 1 --url "http://localhost:8080" --token "Axxxxxxxxxxxxxx" -t "Cron Demo" "via Cronjob"
```
It does NOT matter which username you add. "dummy" or "root" or "something" is ok.

PS: A note:  In my mind there was also am issue with $HOME variable. But in my tests from today $HOME is not needed.

### PR DESCRIPTION
**Pull request by eternal-flame-AD**
This fixes #13

### CODE REVIEW

File: config/locations.go [hunk 1]
```diff
@@ -4,25 +4,25 @@ import (
...
-	etcPath := "/etc/gotify/cli.json"
-	relativePath := "./cli.json"
-	if runtime.GOOS == "windows" {
-		return []string{relativePath, inUserDir}
-	} else {
-		return []string{relativePath, inUserDir, etcPath}
+func GetLocations() (res []string) {
+	res = append(res, "./cli.json")
+
+	if usrDir, err := userDir(); err != nil {
```
Comment (jmattheis) [inline config/locations.go]: user.current can now be used directly.
```suggestion
	if usr, err := user.Current(); err != nil {
```

**Comment by eternal-flame-AD** [comment]
@jmattheis Can you merge this? I don't have the permission.

**Comment by jmattheis** [comment]
Could you retry it? Hopefully I've now fixed it for all repo's. Sorry (:.
